Title：Comparing the weather patterns and CO₂ trends of two cities
Group member： Yinqi Wang & Uli Rodriguez
Description：We want to compare the weather (including the temperature and the number of rainy days) and CO2 trends of two cities located at the same latitude. So we chose Rome and Chicago. Both of them are roughly at the same latitude of 41°N. Through NOAA, I obtained the temperature and precipitation data for Chicago from 2025-1-1 to 2025-7-1, and through Visualcrossing I got the temperature and precipitation for Rome. 

